server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://192.168.13.100:3306/property_management?useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB

  redis:
    port: 6379
    host: 192.168.13.100
    database: 0

mybatis:
  type-aliases-package: com.heng.property_manager.pojo.entity,com.heng.property_manager.pojo.vo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.heng.property_manager.mapper: debug